services:
  auth_service:
    build: backend/auth/
  timesheets_service:
    build: backend/timesheets/
  api_gateway:
    build: api_gateway/
    ports: 
      - 8080:80
    depends_on:
      - auth_service
      - timesheets_service
  frontend_angular:
    build: frontend/angular/
    ports: 
      - 8081:80
  frontend_vue:
    build: frontend/vue/
    ports: 
      - 8082:80
  frontend_react:
    build: frontend/react/
    ports: 
      - 8083:80