services:
  auth_service:
    build: backend/auth/
  timesheets_service:
    build: backend/timesheets/
  frontend_angular:
    build: frontend/angular/
    ports: 
      - 8081:80
  api_gateway:
    build: api_gateway/
    ports: 
      - 8080:80
    depends_on:
      - auth_service
      - timesheets_service