"""made code not unique in projects and tasks

Revision ID: 0d86dd1fe2c5
Revises: cb28ba28f32d
Create Date: 2026-09-07 20:41:29.321353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d86dd1fe2c5'
down_revision: Union[str, Sequence[str], None] = 'cb28ba28f32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_code_key'), 'project', type_='unique')
    op.drop_constraint(op.f('task_code_key'), 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('task_code_key'), 'task', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('project_code_key'), 'project', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
