"""added craeted_at and updated_at columns to record table

Revision ID: a39a0c3ffdce
Revises: 1a16cbbb8c22
Create Date: 2026-09-05 00:23:40.972573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39a0c3ffdce'
down_revision: Union[str, Sequence[str], None] = '1a16cbbb8c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('record', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'updated_at')
    op.drop_column('record', 'created_at')
    # ### end Alembic commands ###
