"""added comment column

Revision ID: c5d6ccb4f74f
Revises: d98934590b0f
Create Date: 2026-08-24 19:56:03.000108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d6ccb4f74f'
down_revision: Union[str, Sequence[str], None] = 'd98934590b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('comment', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'comment')
    # ### end Alembic commands ###
