"""added user_id to projects and tasks

Revision ID: cb28ba28f32d
Revises: a39a0c3ffdce
Create Date: 2026-09-07 20:35:48.263438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb28ba28f32d'
down_revision: Union[str, Sequence[str], None] = 'a39a0c3ffdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_id')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
